### ISSUE TITLE
Does this work on Chinese USB Fans?

### ISSUE THREAD

**Issue by Zerokami** [Ventto/dreamyfan#12]
Does this work on Chinese fans like the ones you can by from Aliexpress.

Or this one for example https://www.amazon.in/Captcha-Programmable-Message-Fan-Drawing/dp/B0772SYZ15/

Or this is a PerFan vendor specific drive.

Thanks!

**Comment by Ventto** [comment]
Hello @Logmytech,
Thanks for considering the support.

Yes, it does !
As the Pearl's one, it is a 11-LED USB fan with the same protocol.
