### ISSUE TITLE
compatible devices list

### ISSUE THREAD

**Issue by toastbrotch** [Ventto/dreamyfan#9]
is it this one? https://aliexpress.com/item/Mini-Gadget-USB-LED-light-Fan-Flexible-Programmable-LED-Cooling-Fan-DIY-Programming-Any-Characters-Messages/32706568703.html which is sold everywhere on aliexpress much cheaper than pearl?

**Comment by Ventto** [comment]
Visually, it's almost the same a 11-LEDs USB Fan with re-programming interface.
This is the [Pearl one](https://www.pearl.fr/article/PX5939/ventilateur-usb-programmable-avec-message-defilant). Hope, the protocol is the same.
Feel free to tell me if the *pearlfan* works with it.
